### ISSUE TITLE
Issue with preprocess-roberta-classifier.sh

### ISSUE THREAD

**Issue by aflah02** [machelreid/lewis#6]
I was checking out the code and couldn't understand this part - 
The command `bash preprocess-roberta-classifer.sh path/to/data <prefix> <domain-1-suffix> <domain-2-suffix>` has 4 command line arguments however inside the `train-roberta-classifier.sh` file only 2 of them are used the last 2 aren't referenced and this causes path issues

**Comment by machelreid** [comment]
Could you elaborate on the "path issues", so I can help fix these? Thank you for pointing all this out!

**Comment by aflah02** [comment]
Hey
Thanks for the highly readable code most academic repos are far from it
So the issue I'm facing persists even when I use the dataset-eval over eval in the command
In the errors thrown there's this line `preprocess-roberta-classifier.sh: line 14: downloads/dataset-eval/train.txt: No such file or directory` which seems to indicate that it's looking for train.txt withing dataset-eval when it should look for it in `downloads/dataset-eval/domain-1-Hate/train.txt` or `downloads/dataset-eval/domain-2-LessHate/train.txt` based on this folder structure - 
<img width="197" alt="image" src="https://user-images.githubusercontent.com/72096386/146874834-75cdfda8-1d8a-40e1-bec7-3a01941ac94f.png">
Upon inspecting the .sh file I looked at how the command line args are being used and noticed that even though 4 command line args are there - 

`path/to/data`
`<prefix>`
`<domain-1-suffix>`
`<domain-2-suffix>`

The code only uses 2 of them as I could only find $1 and $2 and no use of $3 and $4 which would be the extra components of the path so I think maybe that's causing the issue

**Comment by aflah02** [comment]
Alas I realize what a stupid mistake I've been making
Thanks for your time but I believe it's solved

**Comment by aflah02** [comment]
Sorry
The original issue was wrongly written the error comes from `lewis/roberta-classifier/preprocess-roberta-classifier.sh` I thought it was a mistake on my end but I think it's not thought it is using all 4 Command Line Args but still setting up wrong paths

**Comment by aflah02** [comment]
Incase someone faces this issue in the future using an absolute path solved the issue so something like user\xyz\<entire path>
